"""add Department

Revision ID: 050631b18897
Revises: b02d7cb8ae62
Create Date: 2024-11-01 20:15:17.194682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050631b18897'
down_revision = 'b02d7cb8ae62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
